# Generated by Django 5.0.2 on 2025-06-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_channel_subscriptionfolder_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('trending', '急上昇'), ('music', '音楽'), ('gaming', 'ゲーム'), ('news', 'ニュース'), ('sports', 'スポーツ'), ('entertainment', 'エンターテイメント'), ('education', '教育'), ('technology', 'テクノロジー'), ('lifestyle', 'ライフスタイル'), ('comedy', 'コメディ'), ('other', 'その他')], default='other', max_length=20),
        ),
    ]
