# Generated by Django 5.0.2 on 2025-06-21 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_playback_speed', models.FloatField(choices=[(0.25, '0.25x'), (0.5, '0.5x'), (0.75, '0.75x'), (1.0, '標準'), (1.25, '1.25x'), (1.5, '1.5x'), (1.75, '1.75x'), (2.0, '2x'), (2.5, '2.5x'), (3.0, '3x')], default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
