# Generated by Django 5.0.2 on 2025-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_comment_videolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='bio',
            field=models.TextField(blank=True, help_text='チャンネルの紹介文'),
        ),
        migrations.AddField(
            model_name='channel',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='@なしのTwitterハンドル', max_length=50),
        ),
        migrations.AddField(
            model_name='channel',
            name='website',
            field=models.URLField(blank=True, help_text='ウェブサイトURL'),
        ),
    ]
