# Generated by Django 5.0.2 on 2025-06-21 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_channel_bio_channel_twitter_handle_channel_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='有料コンテンツかどうか'),
        ),
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='価格（円）', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', '支払い待ち'), ('completed', '支払い完了'), ('failed', '支払い失敗')], default='pending', max_length=20)),
                ('link_transaction_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaidContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', '動画'), ('channel_subscription', 'チャンネル購読'), ('live_stream', 'ライブ配信'), ('exclusive_content', '限定コンテンツ')], default='video', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='価格（円）', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_contents', to='videos.channel')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_content', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_api_key', models.CharField(blank=True, help_text='Link決済のAPIキー', max_length=255)),
                ('link_secret_key', models.CharField(blank=True, help_text='Link決済のシークレットキー', max_length=255)),
                ('is_payments_enabled', models.BooleanField(default=False, help_text='決済機能を有効にする')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', '支払い待ち'), ('completed', '支払い完了'), ('failed', '支払い失敗'), ('refunded', '返金済み')], default='pending', max_length=20)),
                ('link_transaction_id', models.CharField(blank=True, help_text='Link決済のトランザクションID', max_length=255)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='videos.paidcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'paid_content')},
            },
        ),
    ]
