# Generated by Django 5.0.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_add_db_indexes'),
    ]

    operations = [
        # Add indexes for commonly queried fields
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_video_views ON videos_video(views);",
            reverse_sql="DROP INDEX IF EXISTS idx_video_views;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_video_uploaded_at ON videos_video(uploaded_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_video_uploaded_at;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_video_genre ON videos_video(genre);",
            reverse_sql="DROP INDEX IF EXISTS idx_video_genre;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_video_is_paid ON videos_video(is_paid);",
            reverse_sql="DROP INDEX IF EXISTS idx_video_is_paid;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_comment_video_id ON videos_comment(video_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_comment_video_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_comment_created_at ON videos_comment(created_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_comment_created_at;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_videolike_video_id ON videos_videolike(video_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_videolike_video_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_videolike_user_id ON videos_videolike(user_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_videolike_user_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_subscription_subscriber_id ON videos_subscription(subscriber_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_subscription_subscriber_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_subscription_channel_id ON videos_subscription(channel_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_subscription_channel_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_watchhistory_user_id ON videos_watchhistory(user_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_watchhistory_user_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_watchhistory_watched_at ON videos_watchhistory(watched_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_watchhistory_watched_at;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_watchlater_user_id ON videos_watchlater(user_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_watchlater_user_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_purchase_user_id ON videos_purchase(user_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_purchase_user_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_purchase_status ON videos_purchase(status);",
            reverse_sql="DROP INDEX IF EXISTS idx_purchase_status;"
        ),
    ]