# Generated by Django 5.0.2 on 2025-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_add_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_shorts',
            field=models.BooleanField(default=False, help_text='ショート動画かどうか（60秒以下）'),
        ),
    ]
